### ISSUE TITLE
clEsperanto Assistant needs updated to 18.2 to solve select_gpu

### ISSUE THREAD

**Issue by TimMonko** [haesleinhuepf/devbio-napari#13]
With current conda build, launching naparia from command line shows clEsperanto Assistant in right tool bar which does function correctly. However, trying to call clesperanto assistant from plugin menu results in `TypeError: select_gpu() missing 1 required positional argument: 'viewer'` which had me look into releases for napari-pyclesperanto-assistant and found that this error was fixed in 0.18.2 (https://github.com/clEsperanto/napari_pyclesperanto_assistant/releases). This error also occurs when launching napari from jupyter-lab, making clEsperanto Assistant non-functional. 

I suggest updating the requirements to 0.18.2 for clesperanto Assistant. This has fixed the error in both naparia and jupyter-lab launched napari instances. 

I'll try to make a pull request, but have never done so before so forgive me if I mess up! 

Edit: seems that the napari-pyclesperanto-assistant version on conda-forge is 0.18.0, so will need to be updated to 0.18.2 there.

**Comment by haesleinhuepf** [comment]
Hi @TimMonko ,

thanks for reporting this! Apparently, [napari-pyclesperanto-assistant on conda-forge](https://anaconda.org/conda-forge/napari-pyclesperanto-assistant) has version 0.18.0, which might be the reason why 0.18.2 is not installed in your case. I will try to update it there and then the problem should go away. Updating conda-packages takes about 24h. I keep you posted!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Hi @TimMonko ,

you find now version 0.18.3 on conda-forge. Would you mind testing if installation works in your scenario now?

Thanks!

Best,
Robert

**Comment by TimMonko** [comment]
Thanks Robert! Conda-forge installed 18.3.0 on a fresh environment and now the assistant works in both naparia and jupyter-lab instances of napari.

**Comment by haesleinhuepf** [comment]
Awesome, thanks for reporting the issue @TimMonko !
