### ISSUE TITLE
Incomplete installation of plugins

### ISSUE THREAD

**Issue by EdwinHernandezG** [haesleinhuepf/devbio-napari#26]
Hi

I just noted that after a fresh dev-bio installation, `cellpose-napari` and `napari-process-points-and-surfaces` are not installed, but no error has been shown during the installation.

Only two warnings appeared:
```
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/noarch::nbclassic-0.4.6-pyhd8ed1ab_0, conda-forge/noarch::notebook-6.4.12-pyha770c72_0
  - conda-forge/noarch::nbclassic-0.4.5-pyhd8ed1ab_0, conda-forge/noarch::notebook-6.5.1-pyha770c72done
```

BTW, napari works correctly after installation.

**Comment by haesleinhuepf** [comment]
Thanks for reporting @EdwinHernandezG ! We're working on these here:
* #17 
* https://github.com/haesleinhuepf/napari-process-points-and-surfaces/issues/14
