### ISSUE TITLE
Solving environment failed (installing mamba with conda)

### ISSUE THREAD

**Issue by ursaursic** [haesleinhuepf/devbio-napari#27]
I had some issues installing `mamba` with conda on MacOS (following instructions). I found the solution - this might be helpful to someone who would struggle with the same issue. 

I have the most recent version of anaconda (installer version Anaconda3-2022.10-MacOSX-x86_64), together with python3.9, but when installing mabma with 
`conda install mamba -c conda-forge`
I get this:
Solving environment: failed with initial frozen solve. Retrying with flexible solve. 
Solving environment: failed ...

It takes a lot of time and never manages to solve the environment. 

It turns out that anaconda can be a bit messy because there are already so many packages installed in the base environment. 
In this case, `spyder` is causing problems. 

This was a solution for me:
1. uninstall `spyder` using conda
2. install `mamba` using conda
3. install `spyder` using mamba

The original solved issue, where I got this from:
https://github.com/mamba-org/mamba/issues/1837

**Comment by haesleinhuepf** [comment]
Cool, thanks @ursaursic for letting us know! 💚
