### ISSUE TITLE
torch dependecy

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/devbio-napari#3]
Hi @haesleinhuepf ,

One minor comment/question about the dependencies: When I install devbio-napari, pip automatically downloads torch as well. I think this would be one of the packages that is also best installed through conda since it requires a few more packages to work with GPUS:

According [to the documentation](https://pytorch.org/get-started/locally/), this would look like this:

```
conda install pytorch torchvision cudatoolkit=11.3 -c pytorch
```

torch-functions probably run without these packages, but not with GPU support, I believe.

**Comment by haesleinhuepf** [comment]
Hi @jo-mueller ,

do you know what happens if one installs `cudatoolkit=11.3` on a computer that has no NVidia GPU?

**Comment by jo-mueller** [comment]
Hey @haesleinhuepf ,

> do you know what happens if one installs cudatoolkit=11.3 on a computer that has no NVidia GPU?

haven't tried it, but I would suspect that it throws an error during the installation. torch will also not necessarily complain about not having a GPU at its disposal (provided its used in a way that checks for the presence of a GPU first). It could be added as an optional feature in the Readme somewhere further down.
