### ISSUE TITLE
terminal freezing when trying to follow installation instructions

### ISSUE THREAD

**Issue by allysonryan** [haesleinhuepf/devbio-napari#37]
Hi Robert -- When I try to create a fresh environment to install devbio-napari as instructed on the main page, I get the following error and then the terminal stalls for hours... Can you please have a look at this mamba error? Thanks :)
![Screenshot 2023-04-11 at 11 47 29](https://user-images.githubusercontent.com/15361575/231123902-d36e6f40-d276-44f4-b238-dbe3210104ef.png)

**Comment by haesleinhuepf** [comment]
Hey Allyson @allysonryan ,

could you please run `mamba --version` just to see what it is?

On my computer it does something like this:

![image](https://user-images.githubusercontent.com/12660498/231175183-35eca32d-7dd9-41c0-879e-4be7243d8e4e.png)

**Comment by allysonryan** [comment]
@haesleinhuepf My mamba is apparently super out of date, but all attempts to update it also result in the terminal freezing for hours... I also cannot even manage to uninstall mamba and start fresh :'(
![Screenshot 2023-04-11 at 15 20 28](https://user-images.githubusercontent.com/15361575/231196325-e3ca3ae9-419a-4b9d-b83e-774ce25b571f.png)

**Comment by haesleinhuepf** [comment]
That sounds like a problem the IT dept can solve 😉

**Comment by allysonryan** [comment]
Already submitted a trouble ticket! :)
