### ISSUE TITLE
on some windows machines, napari crashes when devbio-napari is installed together with aicsimageio

### ISSUE THREAD

**Issue by thawn** [haesleinhuepf/devbio-napari#40]
reproduce as follows:
```
mamba create -n devbio-napari-crash python=3.9 devbio-napari napari-aicsimageio
mamba activate devbio-napari-crash
napari
```
after some time, you are returned to the command line without napari having started

**Comment by thawn** [comment]
vanilla napari works with aicsimageio
we also tried to install some of the devbio-napari dependencies and it kept working. however installing napari-simpleitk-image-processing failed because of conflicts with qt and openssl versions.

**Comment by haesleinhuepf** [comment]
WIP: I can fix the environment by installing this:
```
mamba install libxml2=2.10.4
```

**Comment by haesleinhuepf** [comment]
I can create an environment like this:

```
mamba create -n devbio-napari-fine python=3.9 devbio-napari napari-aicsimageio libxml2=2.10.4
```

And then napari works:

```
conda activate devbio-napari-fine
```

```
napari
```

@zoccoler Would you mind trying out if this also works on your computer? Thanks!

**Comment by thawn** [comment]
@haesleinhuepf nice! I was just able to reproduce this on the HIVE
```
mamba create -n devbio-napari-fine python=3.9 devbio-napari napari-aicsimageio libxml2=2.10.4
mamba activate devbio-napari-fine
napari
```
works fine

```
mamba create -n devbio-napari-broken python=3.9 devbio-napari napari-aicsimageio
mamba activate devbio-napari-broken
napari
```
is broken

in the broken environment I have libxml 2.11.4

I would love to know how you nailed this bug down!

**Comment by haesleinhuepf** [comment]
> I would love to know how you nailed this bug down!

I used the two environments we created in the group meeting today and compared them using [beyond compare](https://www.scootersoftware.com/). The napari in the environment on the left is broken, the one on the right works, and has no devbio-napari installed:

![image](https://github.com/haesleinhuepf/devbio-napari/assets/12660498/aacef0eb-3f58-4049-85e5-fd7d3995e240)

I went through all dependencies which are installed in both environments and have a higher version in the environment which is broken. Assuming that a higher version broke the setup (it used to work in the past), I downgraded these:

```
mamba install xarray=2023.1.0 
mamba install svt-av1=1.4.1 
mamba install scipy=1.9.1
mamba install scikit-image=0.19.3
mamba install libxml2=2.10.4
```
After each install command I tested napari. After the last command, napari worked again. This took 30 minutes. 🙌

**Comment by thawn** [comment]
Cool, thanks for sharing your debugging workflow 🥳

**Comment by zoccoler** [comment]
> @zoccoler Would you mind trying out if this also works on your computer? Thanks!

Hi @haesleinhuepf,

It worked! I was able to open and use the Assistant and I was able to open a `.czi` image as well.

**Comment by haesleinhuepf** [comment]
Awesome. Thanks for confirming!
