### ISSUE TITLE
npe2 0.7.0 breaks (all) reader plugins

### ISSUE THREAD

**Issue by thawn** [haesleinhuepf/devbio-napari#41]
it seems that npe2=0.7.0 breaks all reader plugins (at least all that I tested were affected), unless "Use npe2 adaptor" is activated under preferences, which breaks the tools menu.

See 
https://github.com/napari/napari/issues/5837
https://github.com/AllenCellModeling/napari-aicsimageio/issues/77

Hence, I suggest to pin npe2 to <0.7.0

**Comment by haesleinhuepf** [comment]
Hi @thawn ,

there is devbio-napari 0.10.1 available on pypi and conda, which should avoid this problem. Would you mind installing and testing it?

https://github.com/haesleinhuepf/devbio-napari/releases/tag/0.10.1

Thanks!

Best,
Robert

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

I tested this on Windows 10 and it works:

`mamba create -n devbio-napari-env python=3.9 devbio-napari napari-aicsimageio bioformats_jar`

I could open a `.czi` 3D image and I could run operations from the Assistant on it.

**Comment by zoccoler** [comment]
These are the relevant versions I got installed in the environment:

```
npe2                      0.6.2              pyhd8ed1ab_0    conda-forge
napari                    0.4.17          pyh275ddea_0_pyqt    conda-forge
napari-aicsimageio        0.7.2              pyhd8ed1ab_0    conda-forge
aicsimageio               4.10.0             pyhd8ed1ab_0    conda-forge
devbio-napari             0.10.1           win_h08f2357_0    conda-forge
bioformats_jar            2020.5.27          pyhd8ed1ab_0    conda-forge

```

**Comment by thawn** [comment]
I tested it on mac and it works there also. Thanks a lot!
