### ISSUE TITLE
minor fix at documentation

### ISSUE THREAD

**Issue by zoccoler** [haesleinhuepf/devbio-napari#6]
Hi @haesleinhuepf ,

Just a minor thing I noticed: line 73 Readme.md is written `naparia` instead of `napari`. xD

Best,
Marcelo

**Comment by haesleinhuepf** [comment]
Hey Marcelo @zoccoler ,

try it out, it's not a typo! 🌻

Best,
Robert

**Comment by zoccoler** [comment]
Ah I see, it would already open with the assistant! 😻 

But I tried in a new environment and the command was not recognized 😢 
Is there anything I can send you to check what went wrong for me?

**Comment by haesleinhuepf** [comment]
Oh that's interesting! Could you please post the content of napari's menu `Help > Napari info`? I'm suspecting some version mismatch of napari-assistant...

**Comment by zoccoler** [comment]
Sure! Here it goes

```
napari: 0.4.15
Platform: Windows-10-10.0.17763-SP0
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:18:12) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.04.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8729
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1280x720, scale 3.0
- screen 2: resolution 1280x720, scale 3.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.16.0
- console: 0.0.4
- devbio_napari: 0.4.0
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.6.8
- napari-assistant: 0.1.8
- napari-brightness-contrast: 0.1.7
- napari-clusters-plotter: 0.3.0
- napari-crop: 0.1.5
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-ome-zarr: 0.4.0
- napari-plugin-search: 0.1.3
- napari-segment-blobs-and-things-with-membranes: 0.2.21
- napari-simpleitk-image-processing: 0.2.6
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.11
- napari-workflow-optimizer: 0.1.3
- napari_skimage_regionprops1: 0.4.1
- napari_skimage_regionprops2: 0.4.1
- scikit-image: 0.4.15
- svg: 0.1.6
```

**Comment by haesleinhuepf** [comment]
Ok, I just confirmed that behaviour in a fresh environment! I'm going to update the documentation and the PR will close this issue :-)

Big thanks for reporting @zoccoler !

**Comment by zoccoler** [comment]
You are welcome! This issue got longer than I thought 😄 , but I am glad it helped!

**Comment by haesleinhuepf** [comment]
I presume this discussion will bring the fix:
- https://github.com/conda-forge/napari-assistant-feedstock/issues/9
